### ISSUE TITLE
Typekit fonts loading sporadically

### ISSUE THREAD

**Issue by seanwash** [GuillaumeLeclerc/vue-seo#1]
Hey,

First off, thanks for this - it really saved me a lot of work today! The only thing I'm noticing so far is that when using these components that Typekit fonts seem to load sporadically. I haven't had too much of a chance to check it out yet, just something I noticed. I'll do a bit of digging to see if I can't figure it out, but I figured I'd put this on your radar.

**Comment by GuillaumeLeclerc** [comment]
Thank you for your feedback.

Can you show me how you are including your fonts ?

**Comment by seanwash** [comment]
Sure, I just have two script tags in the head of my page, like so

```
<head>
    <script src="https://use.typekit.net/xxxxxxx.js"></script>
    <script>try{Typekit.load({ async: true });}catch(e){}</script>
</head>
```

The same thing occurs if I place the script tags at the bottom of body as well.

**Comment by seanwash** [comment]
Actually I think I might have fixed it. As I was pasting that I noticed the async setting and removed it. That seems to have fixed my problem for now.

**Comment by GuillaumeLeclerc** [comment]
Cool, feel free to reopen if you still have a problem
