### ISSUE TITLE
Facebook graph api

### ISSUE THREAD

**Issue by darbaoui** [GuillaumeLeclerc/vue-seo#5]
facebook graph api cannot load meta 

i'm used mehode to despatch all info about each current page to parent that content all meta compontent of seo

but if i test that in facebook debug tools i have this issue

![screen shot 2016-07-13 at 18 41 17](https://cloud.githubusercontent.com/assets/6907747/16813525/cbf1be56-4929-11e6-97d2-439d42c89863.png)

meta tags in my home page is loaded but not detected by facebook
![screen shot 2016-07-13 at 18 42 00](https://cloud.githubusercontent.com/assets/6907747/16813554/edc638ea-4929-11e6-8ab3-28a4c92c8640.png)

**Comment by GuillaumeLeclerc** [comment]
It's because facebook does not run javascript. And these tags are set by vue (That run in javascript).

You need to use a prerenderer to fix this.

Hope it helps

**Comment by darbaoui** [comment]
thank you

**Comment by seanwash** [comment]
@darbaoui if you need a quick place to start check out prerender.io or snapsearch.io. I'm using the latter and it works fine.

**Comment by darbaoui** [comment]
@seanwash Thanks you , I'm using prerender.io that fixe my PB.

**Comment by seanwash** [comment]
@GuillaumeLeclerc I think this can be closed out now :)
